version: "3.1"
services:
  db:
    image: mysql:8.1
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: db_appsalon
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - ./mysql:/var/lib/mysql
    networks:
      - default
  www:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    ports:
      - 8000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
volumes:
  mysql:
